name: No Response

# Both `issue_comment` and `scheduled` event types are required for this Action
# to work properly.
on:
  issue_comment:
    types: [created]
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: '5 * * * *'

permissions: {}

jobs:
  noResponse:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: MBilalShafi/no-response-add-label@9657b5bc1e09373e571df54429c3c167edaad556
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Number of days of inactivity before an Issue is closed for lack of response
          daysUntilClose: 0
          # Label requiring a response
          responseRequiredLabel: 'status: waiting for follow-up'
          # Comment to post when closing an Issue for lack of response. Set to `false` to disable
          optionalFollowupLabel: 'status: waiting for maintainer response'
          closeComment: >
            The issue has been inactive for 7 days and has been automatically closed.
            If you think that it has been incorrectly closed, please reopen it and provide missing information (if any) or continue the last discussion.
