name: Run when an issue is closed and log the output

on:
  issues:
    types: [closed]

jobs:
  add-tag:
    runs-on: ubuntu-latest
    
    steps:
      - name: "log stuff"
        run: echo '${{ toJSON(github) }}' | jq
        shell: bash
