name: Run when an issue is closed and log the output

on:
  issues:
    types: [closed, reopened]

jobs:
  add-tag:
    runs-on: ubuntu-latest
    
    steps:
      - name: "log stuff"
        if: github.event_name == 'issues' && github.event.action == 'reopened'
        run: echo '${{ toJSON(github) }}' | jq
        shell: bash
