name: Run a workflow every time a comment is dropped on an issue

on:
  issue_comment:
    types: [created]

jobs:
  add-tag:
    runs-on: ubuntu-latest
    steps:
      - name: "log stuff"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
